name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Ou a branch que você usa para produção

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: <your-acr-name>.azurecr.io
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t <your-acr-name>.azurecr.io/<your-image-name>:latest .
        docker push <your-acr-name>.azurecr.io/<your-image-name>:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-webapp-name>
        slot-name: production
        images: <your-acr-name>.azurecr.io/<your-image-name>:latest
